In [1]:
import numpy as np

In [2]:
# 1.1 Creating a vector

row_vector = np.array([1,2,3,4]) # row vector
column_vector = np.array([[1],
                           [2],
                           [3],
                           [4]])


In [3]:
# 1.2 creating a matrix

matrix = np.array([[1,2],
                   [3,4],
                   [5,6]])
matrix

array([[1, 2],
       [3, 4],
       [5, 6]])

In [4]:
# 1.3 Creating a sparse matrix

from scipy import sparse

matrx = np.array([[0, 0],
                 [0, 1],
                 [3, 0]])

sparse_matrix = sparse.csr_matrix(matrx)
print(sparse_matrix)
matrix_large = np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                         [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
                         [3, 0, 0, 0, 0, 0, 0, 0, 0, 0]])
matrix_large_sparse = sparse.csr_matrix(matrix_large)
print(matrix_large_sparse)

  (1, 1)	1
  (2, 0)	3
  (1, 1)	1
  (2, 0)	3


In [5]:
# 1.4 Selecting elements

vector = np.array([1, 2, 3, 4, 5, 6])
# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print(vector[1])

print(matrix[2])
print(matrix[2][2])

2
[7 8 9]
9


In [6]:
# 1.5 Describing a Matrix

matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

print(matrix.shape)
print(matrix.size)
print(matrix.ndim)

(3, 4)
12
2


In [10]:
# 1.6 Applying Operations to elements

import numpy as np
# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

add_100 = lambda i: i+100
vectorized_add_100 = np.vectorize(add_100)

vectorized_add_100(matrix)
# Broadcasting

matrix + 100

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [13]:
# 1.7 Finding the Maximum and Minimum Values

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
# Return maximum element
np.max(matrix)
np.min(matrix)
# Find maximum element in each column
np.max(matrix, axis=0)
# Find maximum element in each row
np.max(matrix, axis=1)

1

In [16]:
# 1.8 Calculating the Average, Variance, and Standard Deviation

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])


# average

np.mean(matrix)

# variance

np.var(matrix)

# Std

np.std(matrix)

2.581988897471611

In [26]:
# 1.9 Reshaping Arrays

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],
                   [10, 11, 12]])
# Reshape matrix into 2x6 matrix
matrix.reshape(2,6)
# first is rows second is all columns
matrix.reshape(1,-1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [23]:
# 1.10 Transpose

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
# Transpose matrix
matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [28]:

# 1.11 Flattening a Matrix

import numpy as np
# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
# Flatten matrix
matrix.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
# 1.12 Finding the Rank of a Matrix
matrix = np.array([[1, 1, 1],
                   [1, 1, 10],
                   [1, 1, 15]])
# Return matrix rank
np.linalg.matrix_rank(matrix)

2

In [31]:
# 1.13 Calculating the Determinant
matrix = np.array([[1, 2, 3],
                   [2, 4, 6],
                   [3, 8, 9]])
np.linalg.det(matrix)

0.0

In [34]:
# 1.14 Getting the Diagonal of a Matrix

matrix = np.array([[1, 2, 3],
                   [2, 4, 6],
                   [3, 8, 9]])

print(matrix.diagonal())
# Смещение
matrix.diagonal(offset=1)

[1 4 9]


array([2, 6])

In [35]:
#1.15 Calculating the Trace of a Matrix

matrix.trace()

14

In [36]:
# 1.16 Finding Eigenvalues and Eigenvectors

matrix = np.array([[1, -1, 3],
                   [1, 1, 6],
                   [3, 8, 9]])

eigenvalues, eigenvectors = np.linalg.eig(matrix)

print(eigenvalues)
print(eigenvectors)

[13.55075847  0.74003145 -3.29078992]
[[-0.17622017 -0.96677403 -0.53373322]
 [-0.435951    0.2053623  -0.64324848]
 [-0.88254925  0.15223105  0.54896288]]


In [37]:
# 1.17 Calculating Dot Products

vector_a = np.array([1,2,3])
vector_b = np.array([4,5,6])

np.dot(vector_a, vector_b)

32

In [39]:
# 1.18 Adding and Subtracting Matrices

matrix_a = np.array([[1, 1, 1],
                     [1, 1, 1],
                     [1, 1, 2]])

matrix_b = np.array([[1, 3, 1],
                     [1, 3, 1],
                     [1, 3, 8]])

print(np.add(matrix_a, matrix_b))

np.subtract(matrix_a, matrix_b)


[[ 2  4  2]
 [ 2  4  2]
 [ 2  4 10]]


array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])

In [40]:
# 1.19 Multiplying Matrices

np.dot(matrix_b, matrix_a)

array([[ 5,  5,  6],
       [ 5,  5,  6],
       [12, 12, 20]])

In [41]:
# 1.20 Inverting a Matrix

matrix = np.array([[1, 4],
                   [2, 5]])
# Calculate inverse of matrix
np.linalg.inv(matrix)


array([[-1.66666667,  1.33333333],
       [ 0.66666667, -0.33333333]])

In [44]:
# 1.21 Generating Random Values

# Set seed
np.random.seed(0)
# Generate three random floats between 0.0 and 1.0
print(np.random.random(3))
print(np.random.randint(0, 11, 3))

print(np.random.normal(0.0, 1.0, 3))

print(np.random.logistic(0.0, 1.0, 3))

np.random.uniform(1.0, 2.0, 3)

[0.5488135  0.71518937 0.60276338]
[3 7 9]
[-1.42232584  1.52006949 -0.29139398]
[-0.98118713 -0.08939902  1.46416405]


array([1.47997717, 1.3927848 , 1.83607876])